-- return {
--     'jose-elias-alvarez/null-ls.nvim',
--     branch = 'main',
--     lazy = false,
--     dependencies = {
--         {
--             'nvim-lua/plenary.nvim',
--             tag = 'v0.1.4',
--         }
--     },
--     config = function()
--         local augroup = vim.api.nvim_create_augroup('LspFormatting', {})
--         local null_ls = require('null-ls')
--         null_ls.setup({
--             sources = {
--                 null_ls.builtins.formatting.black,
--                 null_ls.builtins.formatting.isort,
--             },
--
--             on_attach = function(client, bufnr)
--                 if client.supports_method("textDocument/formatting") then
--                     vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
--                     vim.api.nvim_create_autocmd("BufWritePre", {
--                         group = augroup,
--                         buffer = bufnr,
--                         callback = function()
--                             vim.lsp.buf.format()
--                         end,
--                     })
--                 end
--             end,
--         })
--     end,
-- }

return {}
